source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'MXHotfix_Example', :exclusive => true do
  pod 'MXHotfix', :path => '../'
end

target 'MXHotfix_Tests', :exclusive => true do
  pod 'MXHotfix', :path => '../'

  
end
