source 'https://github.com/CocoaPods/Specs.git'

target 'MXHotfix_Example', :exclusive => true do
  pod 'MXHotfix', :path => '../'
end

target 'MXHotfix_Tests', :exclusive => true do
  pod 'MXHotfix', :path => '../'

  
end
